"""
SecureChain Blockchain Router
Isolated backend API layer for blockchain transaction creation, retrieval, verification, statistics, and activity.
Does not touch or modify existing GSTAPP collections or APIs.
"""

import secrets
import random
import logging
from datetime import datetime, timezone
from typing import Optional, Dict, Any, List

from fastapi import APIRouter, Request, HTTPException, Query, status
from pydantic import BaseModel, Field, model_validator

from utils import get_user_email, create_access_token
from blockchain.database import (
    create_transaction,
    get_user_transactions,
    get_transaction_by_id,
    count_user_transactions,
    get_blockchain_stats,
    get_blockchain_activity,
    ensure_user_seeded,
)
from securechain.services.engine import engine
from securechain.services.graph_service import graph_service

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Route 0: POST /api/blockchain/auth/demo-token ────────────────────────────

@router.post("/auth/demo-token")
async def get_demo_token(request: Request):
    """Generates an authenticated session token for SecureChain demo exploration or session refresh."""
    email = "alex.mercer@securechain.io"
    try:
        body = await request.json()
        if isinstance(body, dict) and body.get("email"):
            email = str(body["email"]).strip()
    except Exception:
        pass
    await ensure_user_seeded(email)
    token = create_access_token({"sub": email})
    name_part = email.split("@")[0].replace(".", " ").title()
    return {
        "success": True,
        "token": token,
        "user_email": email,
        "user_name": name_part
    }


# ── Pydantic Request Schemas & Input Validation ──────────────────────────────

class TransactionCreateInput(BaseModel):
    """
    Validated schema for creating a new blockchain transaction.
    User does NOT supply transaction ID, nonce, timestamp, signature, or hash.
    These are strictly generated by the backend.
    """
    receiver_id: str = Field(..., min_length=3, max_length=128, description="Receiver wallet address or node ID")
    amount: float = Field(..., gt=0, le=100_000_000, description="Transaction transfer quantity (must be > 0)")
    description: str = Field(..., min_length=1, max_length=500, description="Audit memo or description")
    transaction_type: Optional[str] = Field(default="Standard Transfer", description="Type of transaction")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Arbitrary transaction metadata")

    @model_validator(mode="before")
    @classmethod
    def normalize_fields(cls, data: Any):
        if isinstance(data, dict):
            # Normalize receiver_id aliases (receiverId, recipient_address, recipientAddress)
            if not data.get("receiver_id"):
                for alias in ["receiverId", "recipient_address", "recipientAddress"]:
                    if data.get(alias):
                        data["receiver_id"] = data[alias]
                        break

            # Normalize transaction_type aliases (txType, transactionType)
            if not data.get("transaction_type"):
                for alias in ["txType", "transactionType"]:
                    if data.get(alias):
                        data["transaction_type"] = data[alias]
                        break
        return data


# ── Route 1: POST /api/blockchain/transactions ───────────────────────────────

@router.post("/transactions", status_code=status.HTTP_201_CREATED)
async def submit_transaction(req: TransactionCreateInput, request: Request):
    """
    Create and record a new transaction in the SecureChain ledger.
    - Uses authenticated user identity
    - Generates transaction ID on the backend
    - Generates nonce on the backend
    - Generates timestamp on the backend
    - Validates inputs strictly
    - Stores transaction in SecureChainDB.blockchain_transactions
    """
    user_email = get_user_email(request)
    await ensure_user_seeded(user_email)

    # Validate input receiver
    clean_receiver = req.receiver_id.strip()
    if not clean_receiver:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Receiver ID / wallet address cannot be empty."
        )

    clean_description = req.description.strip()
    if not clean_description:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Transaction description / memo cannot be empty."
        )

    # Execute full cryptographic engine lifecycle flow:
    # Generate Tx ID -> Nonce -> Timestamp -> SHA-256 Hash -> ECDSA Signature -> Verify Signature -> Validate Tx -> Add to Block -> Link Prev Hash -> Calculate Block Hash -> Store Record
    success, tx, block, result_meta = await engine.execute_transaction_flow(
        user_email=user_email,
        receiver_id=clean_receiver,
        amount=round(float(req.amount), 4),
        description=clean_description,
        transaction_type=req.transaction_type or "Standard Transfer",
        metadata=req.metadata or {}
    )

    if not success:
        return {
            "success": False,
            "message": result_meta.get("message", "INTEGRITY CHECK FAILED"),
            "error": result_meta.get("error"),
            "transaction": tx.to_dict() if tx else None,
            "validation": result_meta
        }

    return {
        "success": True,
        "message": "Transaction cryptographically validated and added to blockchain block.",
        "transaction": tx.to_dict(),
        "block": block.to_dict() if block else None,
        "validation": result_meta
    }


# ── Route 2: GET /api/blockchain/transactions/my ─────────────────────────────

@router.get("/transactions/my")
async def get_my_transactions(
    request: Request,
    page: int = Query(1, ge=1, description="Page number"),
    limit: int = Query(50, ge=1, le=200, description="Items per page"),
    status: Optional[str] = Query(None, description="Optional status filter: VALID, PENDING, REJECTED")
):
    """
    List all transactions belonging to the authenticated user.
    Enforces user isolation: users can ONLY view their own transactions.
    """
    user_email = get_user_email(request)

    skip = (page - 1) * limit
    transactions, total = await get_user_transactions(
        user_email=user_email,
        skip=skip,
        limit=limit,
        status=status
    )

    return {
        "success": True,
        "user_email": user_email,
        "page": page,
        "limit": limit,
        "total": total,
        "transactions": transactions
    }


# ── Route 3: GET /api/blockchain/transactions/{transaction_id} ───────────────

@router.get("/transactions/{transaction_id}")
async def get_single_transaction(transaction_id: str, request: Request):
    """
    Retrieve single transaction by transaction_id.
    Enforces user isolation: rejects access if the transaction belongs to another user.
    """
    user_email = get_user_email(request)
    await ensure_user_seeded(user_email)

    tx = await get_transaction_by_id(transaction_id, user_email=user_email)
    if not tx:
        foreign_tx = await get_transaction_by_id(transaction_id)
        if foreign_tx and foreign_tx.get("user_email") != user_email:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Access denied: You are only authorized to view your own transactions."
            )
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction '{transaction_id}' was not found in the SecureChain ledger."
        )

    return {
        "success": True,
        "transaction": tx
    }


# ── Route 4: POST /api/blockchain/transactions/{transaction_id}/verify ───────

@router.post("/transactions/{transaction_id}/verify")
async def verify_transaction(transaction_id: str, request: Request):
    """
    Cryptographic verification endpoint for a transaction:
    - Validates user ownership
    - Audits SHA-256 payload integrity
    - Verifies SECP256K1 digital signature
    - Verifies block linkage and Merkle tree root
    - Returns 'TRANSACTION VERIFIED' or 'INTEGRITY CHECK FAILED'
    """
    user_email = get_user_email(request)
    await ensure_user_seeded(user_email)

    is_valid, report = await engine.verify_transaction_on_chain(transaction_id, user_email)
    if "error" in report:
        if report["error"] == "ACCESS_DENIED":
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=report["message"]
            )
        elif report["error"] == "NOT_FOUND":
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=report["message"]
            )
    return report


# ── Route 5: GET /api/blockchain/stats ───────────────────────────────────────

@router.get("/stats")
async def get_stats(request: Request):
    """
    Retrieve real-time ledger and user transaction statistics.
    Returns Total, Valid, Pending, and Rejected counts along with block heights.
    """
    user_email = get_user_email(request)
    stats_data = await get_blockchain_stats(user_email)
    return {
        "success": True,
        **stats_data
    }


# ── Route 6: GET /api/blockchain/activity ────────────────────────────────────

@router.get("/activity")
async def get_blockchain_activity_endpoint(request: Request):
    """
    Retrieve recent blockchain network activity, confirmed transaction metrics,
    latest block number, block hash, and validator consensus events.
    """
    user_email = get_user_email(request)
    activity_data = await get_blockchain_activity(user_email)
    return {
        "success": True,
        **activity_data
    }


# ── Route 7: GET /api/blockchain/graph ───────────────────────────────────────

@router.get("/graph")
async def get_blockchain_graph_endpoint(
    request: Request,
    limit: int = Query(100, ge=1, le=500, description="Maximum nodes to retrieve from Neo4j")
):
    """
    Retrieve graph representation of blockchain entities from Neo4j:
    - User nodes (without private keys)
    - Transaction nodes (transaction_id, sender, receiver, amount, nonce, timestamp, hash, signature, status)
    - Block nodes (block_number, timestamp, previous_hash, block_hash)
    - Relationships: CREATED, INCLUDED_IN, PREVIOUS_BLOCK
    """
    user_email = get_user_email(request)
    await ensure_user_seeded(user_email)

    graph_data = await graph_service.get_blockchain_graph(limit=limit)
    return {
        "success": True,
        "database": "Neo4j Aura",
        **graph_data
    }


# ── Route 8: POST /api/blockchain/graph/sync ─────────────────────────────────

@router.post("/graph/sync")
async def sync_blockchain_graph_endpoint(request: Request):
    """
    Trigger complete ledger synchronization from SecureChain ledger into Neo4j.
    Idempotent operation using MERGE.
    """
    user_email = get_user_email(request)
    await ensure_user_seeded(user_email)

    # Synchronize chain blocks
    result = await graph_service.sync_entire_chain(chain_manager=engine.chain_manager)

    # Also synchronize all user transactions
    user_txs, _ = await get_user_transactions(user_email, skip=0, limit=500)
    synced_user_txs = 0
    for tx in user_txs:
        if await graph_service.sync_transaction(tx):
            synced_user_txs += 1

    result["synced_user_transactions"] = synced_user_txs

    return {
        "success": True,
        "message": "SecureChain ledger synchronized with Neo4j graph database.",
        **result
    }


# ── Route 9: GET /api/blockchain/graph/status ────────────────────────────────

@router.get("/graph/status")
async def get_blockchain_graph_status(request: Request):
    """Check connectivity and schema status for the SecureChain Neo4j instance."""
    conn_status = graph_service.check_connection()
    return {
        "success": conn_status.get("connected", False),
        **conn_status
    }


# ── Route 10: GET /api/blockchain/blocks ─────────────────────────────────────

@router.get("/blocks")
async def get_blockchain_blocks_endpoint(
    request: Request,
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    order: str = Query("asc", description="'asc' for chain index order or 'desc' for newest first")
):
    """
    Retrieve real confirmed blocks from the active SecureChain blockchain ledger.
    """
    get_user_email(request)
    chain = await engine.chain_manager.get_chain(limit=1000)
    if order.lower() == "desc":
        chain_sorted = sorted(chain, key=lambda b: b.index, reverse=True)
    else:
        chain_sorted = sorted(chain, key=lambda b: b.index)
    total = len(chain_sorted)
    skip = (page - 1) * limit
    page_blocks = chain_sorted[skip : skip + limit]

    return {
        "success": True,
        "total": total,
        "page": page,
        "limit": limit,
        "blocks": [b.to_dict() for b in page_blocks]
    }


# ── Route 11: GET /api/blockchain/blocks/{block_id} ──────────────────────────

@router.get("/blocks/{block_id}")
async def get_blockchain_block_by_id_endpoint(block_id: str, request: Request):
    """
    Retrieve single block and its complete transaction payloads by block_id or index.
    """
    get_user_email(request)
    block = await engine.chain_manager.get_block_by_id(block_id)
    if not block:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Block '{block_id}' not found in blockchain ledger."
        )
    return {
        "success": True,
        "block": block.to_dict()
    }


# ── Route 12: POST /api/blockchain/blocks/verify-chain ───────────────────────

@router.post("/blocks/verify-chain")
async def verify_blockchain_chain_endpoint(request: Request):
    """
    Audit and mathematically verify the entire blockchain ledger sequence.
    """
    get_user_email(request)
    from securechain.validation.chain_validator import ChainValidator
    chain = await engine.chain_manager.get_chain(limit=2000)
    is_valid, first_invalid_block, summary_message, audit_report = ChainValidator.validate_chain_integrity(chain)
    return {
        "success": True,
        "is_valid": is_valid,
        "total_blocks": audit_report["total_blocks_checked"],
        "verified_blocks": audit_report["verified_blocks"],
        "first_invalid_block": first_invalid_block,
        "error_reason": audit_report["error_reason"],
        "corrupted_block_indices": audit_report["corrupted_block_indices"],
        "message": summary_message,
        "audit_report": audit_report
    }

